connector:
  jira_url: https://issues.apache.org/jira
  thread_count: 10
  issue_in_request: 100
  max_time_sleep: 8000
  min_time_sleep: 50

database:
  host_db: localhost
  port_db: 5432
  name_db: testdb
  password_db: pgpwd
  user_db: pguser

server:
  api_server:
    host_server: localhost
    port_server: 8080
    api_pref: /api/v1

  connector_http:
    connector_host: localhost
    connector_port: 8003
    connector_pref: /connector